name: create_trophy

on:
#  schedule:
#    - cron: "0 3 * * *"
  workflow_dispatch:
#  push:
#    branches:
#      - main

jobs:
  create-trophy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Generate trophy
        id: trophy
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: ${{ github.repository_owner }}
          file: dist/trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug workspace
        run: |
          pwd
          find . -type f

      - name: Verify SVG generated
        run: |
          if [ -f dist/trophy.svg ]; then
              echo "SVG exists ($(wc -c < dist/trophy.svg) Bytes)"
              file dist/trophy.svg
          else
              echo "SVG failed to generate"
              exit 1
          fi

      - name: Push trophy to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: snake
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
