name: Metrics
on:
  schedule:
     - cron: "0 3 * * *"
 
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@v4.0
        with:
          token: ${{ secrets.METRICS_TOKEN }}
